#!/usr/bin/env ansible-playbook

- name: create EC2 instances
  hosts: localhost
  vars:
    instance_type: m5d.8xlarge
    count: 2 # number of instances per regions
    regions:
      - us-east-1
      - eu-north-1
      - ap-southeast-2
      - us-west-1
      - ap-northeast-1

  tasks:
    - name: install ec2 instances
      include_tasks: ../task/create.yml
      with_items: "{{ regions }}"
      loop_control:
        loop_var: region